stages:
  - stage: build
    jobs:
      - job: build
        pool: optastack
        steps:
          - bash: echo "Building..."
  - stage: test
    jobs:
      - job: build
        pool: optastack
        steps:
          - bash: echo "Testing..."
  - stage: deploy
    jobs:
      - job: deploy
        pool: optastack
        steps:
          - bash: echo "Deploy..."
